name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: SSH and deploy
        env: 
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}} # reference to github secrets
          ec2_url: "ec2-3-111-186-211.ap-south-1.compute.amazonaws.com"
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -i keyfile ubuntu@$ec2_url "sudo bash ~/deploy.sh"